Repository simpledotorg/simple-server, pull requests merged in 2019-10, with the labels that each got.

#538 Move audit logs out of the db
  app/controllers/api/current/appointments_controller.rb
  app/controllers/api/current/medical_histories_controller.rb
  app/controllers/api/current/prescription_drugs_controller.rb
  app/controllers/api/current/sync_controller.rb
  app/controllers/concerns/api/v1/sync_controller_overrides.rb
  app/jobs/create_audit_logs_worker.rb
  app/models/appointment.rb
  app/models/audit_log.rb
  app/models/medical_history.rb
  app/models/prescription_drug.rb
  app/models/user.rb
  app/transformers/api/current/appointment_transformer.rb
  app/transformers/api/current/medical_history_transformer.rb
  app/transformers/api/current/prescription_drug_transformer.rb
  app/transformers/api/v2/appointment_transformer.rb
  app/transformers/api/v2/prescription_drug_transformer.rb
  app/views/admin/audit_logs/index.html.erb
  config/initializers/audit_logger.rb
  db/migrate/20190905131707_add_user_id_to_medical_histories.rb
  db/migrate/20190905131721_add_user_id_to_prescription_drugs.rb
  db/migrate/20190905131736_add_user_id_to_appointments.rb
  db/schema.rb
  lib/tasks/data_clean_up/move_user_recorded_data_to_registration_facility.rb
  spec/controllers/api/current/blood_pressures_controller_spec.rb
  spec/controllers/api/current/logins_controller_spec.rb
  spec/controllers/api/v2/logins_controller_spec.rb
  spec/controllers/shared_examples/shared_spec_for_sync_controller.rb
  spec/factories/appointments.rb
  spec/factories/audlit_logs.rb
  spec/factories/medical_histories.rb
  spec/factories/prescription_drugs.rb
  spec/features/admin/audit_log_spec.rb
  spec/jobs/create_audit_logs_worker_spec.rb
  spec/lib/tasks/data_clean_up/move_user_recorded_data_to_registration_facility_spec.rb
  spec/models/audit_log_spec.rb
  spec/policies/audit_log_policy_spec.rb
  spec/requests/api/current/prescription_drug_sync_spec.rb
  spec/requests/api/v2/prescription_drug_sync_spec.rb
  spec/transformers/api/current/appointment_transformer_spec.rb
  spec/transformers/api/current/medical_history_transformer_spec.rb
  spec/transformers/api/current/prescription_drug_transformer_spec.rb
  spec/transformers/api/v2/appointment_transformer_spec.rb
  spec/transformers/api/v2/medical_history_transformer_spec.rb
  spec/transformers/api/v2/prescription_drug_transformer_spec.rb
Labels: stale-pr

#595 Add an automerge GitHub action
  .github/workflows/automerge.yml
  .github/workflows/stale.yml
Labels: automerge

#581 Update invite admin designs
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/components.js
  app/assets/javascripts/components/common/CollectionCheckBoxes.jsx
  app/assets/javascripts/components/common/CollectionRadioButtons.jsx
  app/assets/javascripts/components/common/SelectField.jsx
  app/assets/javascripts/components/common/TextInputField.jsx
  app/assets/javascripts/components/invite_admin/AccessLevelComponent.jsx
  app/assets/javascripts/components/invite_admin/SelectResource.jsx
  app/assets/javascripts/components/invite_admin/SelectResourceModal.jsx
  app/assets/javascripts/components/invite_admin_form.jsx
  app/assets/javascripts/server_rendering.js
  app/assets/stylesheets/application.scss
  app/controllers/admins_controller.rb
  app/controllers/email_authentications/invitations_controller.rb
  app/models/email_authentication.rb
  app/models/user.rb
  app/models/user_permission.rb
  app/policies/admin_policy.rb
  app/policies/permissions.rb
  app/policies/user_policy.rb
  app/views/admins/_form.html.erb
  app/views/admins/index.html.erb
  app/views/admins/show.html.erb
  app/views/email_authentications/invitations/new.html.erb
  app/views/layouts/application.html.erb
  config/initializers/react_server_rendering.rb
  config/locales/devise_invitable.en.yml
  db/schema.rb
  lib/tasks/scripts/create_master_user.rb
  spec/controllers/email_authentications/invitations_controller_spec.rb
  spec/factories/users.rb
  spec/lib/tasks/scripts/create_master_user_spec.rb
Labels: dependent

#592 Add i18n login api messages for Bangla
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/address.rb
  config/application.rb
  config/locales/bn_BD.yml
  config/locales/mr_IN.yml
  config/locales/pa_Guru_IN.yml
  spec/services/sms_notification_service_spec.rb
Labels: bangladesh

#608 I18n progress tab bengali
  app/views/api/current/analytics/user_analytics/_graph.html.erb
  app/views/api/current/analytics/user_analytics/show.bn.html.erb
Labels: bangladesh, dependent

#604 Add Bengali help screen template
  app/views/api/current/help/show.bn.html.erb
Labels: bangladesh, dependent
