Repository simpledotorg/simple-server, pull requests merged in 2020-11, with the labels that each got.

#1482 Reports JS refactor
  app/assets/javascripts/common/reports.js
  app/views/reports/regions/_visit_details_card.html.erb
Labels: reports

#1481 Reports number formatting with numeral.js
  app/assets/javascripts/application.js
  app/assets/javascripts/common/reports.js
  package.json
  yarn.lock
Labels: reports

#1491 Progress tab "Updated date" fix
  app/assets/stylesheets/user_analytics.scss
  app/views/api/v3/analytics/user_analytics/show.html.erb
Labels: bug

#1495 My Facilities: Comma-formatted numbers
  app/views/my_facilities/blood_pressure_control.html.erb
  app/views/my_facilities/missed_visits.html.erb
  app/views/my_facilities/registrations.html.erb
  app/views/shared/my_facilities/_facilities_by_size.html.erb
  app/views/shared/my_facilities/_inactive_facilities.html.erb
Labels: bug

#1494 Reports: Comma-formatted numbers
  app/views/reports/regions/cohort.html.erb
  app/views/reports/regions/details.html.erb
Labels: bug

#1506 My Facilities: Number formatting
  app/helpers/dashboard_helper.rb
  app/helpers/my_facilities_helper.rb
  app/views/my_facilities/blood_pressure_control.html.erb
  app/views/my_facilities/missed_visits.html.erb
  app/views/my_facilities/registrations.html.erb
  spec/helpers/dashboard_helper_spec.rb
Labels: bug

#1473 Make strong password a bit more lax
  app/models/email_authentication.rb
  spec/models/email_authentication_spec.rb
Labels: stale-pr

#1511 Import missing IHCI blocks
  config/data/india/ihci/canonical_zones.yml
  lib/ihci/data/facility_blocks_list.csv
  lib/tasks/import.rake
  lib/tasks/scripts/import_facility_block_names.rb
  spec/fixtures/files/facility_blocks_list.csv
  spec/tasks/scripts/import_facility_block_names_spec.rb
Labels: block level sync

#1500 Manage zones in facility groups
  app/assets/javascripts/common/facility_group_block_fields.js
  app/assets/stylesheets/partials/_dashboard.scss
  app/controllers/admin/facilities_controller.rb
  app/controllers/admin/facility_groups_controller.rb
  app/models/region.rb
  app/services/manage_district_region_service.rb
  app/views/admin/facilities/_form.html.erb
  app/views/admin/facility_groups/_form.html.erb
  spec/controllers/admin/facility_groups_controller_spec.rb
  spec/models/facility_group_spec.rb
  spec/services/manage_district_region_service_spec.rb
Labels: block level sync

#1512 Freeze and prefill address fields
  app/controllers/admin/facilities_controller.rb
  app/models/facility.rb
  app/models/facility_group.rb
  app/views/admin/facilities/_form.html.erb
  app/views/admin/facilities/upload.html.erb
  app/views/admin/facility_groups/_form.html.erb
  public/documents/upload_facilities.csv
  public/documents/upload_facilities_without_state.csv
  spec/fixtures/files/upload_facilities_invalid_test.csv
  spec/fixtures/files/upload_facilities_test.csv
  spec/fixtures/files/upload_facilities_without_state_test.csv
  spec/models/facility_spec.rb
Labels: block level sync

#1544 Refactor State region creation
  app/assets/javascripts/common/facility_group_block_fields.js
  app/controllers/admin/facility_groups_controller.rb
  app/models/facility_group.rb
  app/services/manage_district_region_service.rb
  app/views/admin/facility_groups/_form.html.erb
  spec/controllers/admin/facility_groups_controller_spec.rb
  spec/factories/facility_groups.rb
  spec/factories/regions.rb
  spec/features/admin/facilities/index_spec.rb
  spec/models/facility_group_spec.rb
  spec/services/manage_district_region_service_spec.rb
Labels: block level sync

#1527 Region callbacks for Facility
  app/models/facility.rb
  app/models/facility_group.rb
  app/models/organization.rb
  spec/controllers/admin/facilities_controller_spec.rb
  spec/controllers/admin/facility_groups_controller_spec.rb
  spec/factories/facilities.rb
  spec/factories/facility_groups.rb
  spec/factories/prescription_drugs.rb
  spec/factories/regions.rb
  spec/features/admin/facilities/index_spec.rb
  spec/models/facility_group_spec.rb
  spec/models/facility_spec.rb
  spec/models/region_spec.rb
  spec/services/region_backfill_spec.rb
  spec/tasks/scripts/import_facility_block_names_spec.rb
Labels: block level sync

#1551 Find or create parent regions in specs
  spec/factories/facilities.rb
  spec/factories/facility_groups.rb
Labels: stale-pr

#1549 Only load Capybara things when running feature specs
  spec/features/admin/facilities/index_spec.rb
  spec/features/admin/organizations/index_spec.rb
  spec/features/admin/passwords/new_spec.rb
  spec/features/admin/protocols/index_spec.rb
  spec/features/admin/protocols/show_spec.rb
  spec/features/admin/sessions/new_spec.rb
  spec/features/admin/users/index_spec.rb
  spec/features/admin/users_spec.rb
  spec/features/admins_spec.rb
  spec/features/appointments/index_spec.rb
  spec/features/appointments_spec.rb
  spec/features/organizations/index_spec.rb
  spec/features_helper.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: stale-pr
