Repository simpledotorg/simple-server, pull requests merged in 2020-09, with the labels that each got.

#1244 Link telemed MO users to facilities
  app/models/facility.rb
  app/models/teleconsultation_medical_officer.rb
  app/models/user.rb
  app/schema/api/v4/models.rb
  app/transformers/api/v4/user_transformer.rb
  db/migrate/20200824112700_facilities_teleconsultation_medical_officers.rb
  db/schema.rb
  spec/factories/teleconsultation_medical_officers.rb
  spec/models/facility_spec.rb
  spec/models/teleconsultation_medical_officer_spec.rb
  spec/models/user_spec.rb
  spec/transformers/api/v4/user_transformer_spec.rb
  swagger/v4/swagger.json
Labels: telemed-mvp

#1208 Permissions: flesh out roles and actions
  .standard_todo.yml
  app/controllers/admin/facilities_controller.rb
  app/controllers/admin/facility_groups_controller.rb
  app/controllers/admin/users_controller.rb
  app/controllers/admin_controller.rb
  app/controllers/concerns/my_facilities_filtering.rb
  app/controllers/email_authentications/invitations_controller.rb
  app/controllers/my_facilities_controller.rb
  app/controllers/organizations_controller.rb
  app/models/user.rb
  app/models/user_access.rb
  app/views/admin/facilities/edit.html.erb
  app/views/admin/facilities/index.html.erb
  app/views/admin/facilities/show.html.erb
  app/views/admin/facility_groups/edit.html.erb
  app/views/admin/facility_groups/index.html.erb
  app/views/admin/facility_groups/show.html.erb
  app/views/layouts/application.html.erb
  app/views/organizations/index.html.erb
  app/views/shared/_user_approvals.html.erb
  config/routes.rb
  spec/controllers/admin/facility_groups_controller_spec.rb
  spec/controllers/admin_controller_spec.rb
  spec/factories/users.rb
  spec/features/admin/facilities/index_with_new_permissions_spec.rb
  spec/features/home_with_new_permissions_spec.rb
  spec/flipper_helper.rb
  spec/models/access_spec.rb
  spec/models/user_access_spec.rb
  spec/models/user_spec.rb
  spec/spec_helper.rb
Labels: simple-permissions

#1262 More efficient tree for displaying access resources
  Gemfile
  Gemfile.lock
  app/controllers/admin/facilities_controller.rb
  app/helpers/admin_access_helper.rb
  app/models/user.rb
  app/models/user_access.rb
  app/models/user_access_tree.rb
  app/presenters/admin_access_presenter.rb
  app/views/admin/facilities/index.html.erb
  app/views/email_authentications/invitations/_access_tree.html.erb
  app/views/email_authentications/invitations/new.html.erb
  app/views/layouts/application.html.erb
  spec/models/user_access_spec.rb
  spec/models/user_spec.rb
Labels: simple-permissions

#1263 More efficient strategy for inviting new admins
  app/models/user_access.rb
  app/presenters/admin_access_presenter.rb
Labels: simple-permissions

#1252 Allow Admins to Edit accesses
  app/assets/javascripts/invite_admin.js
  app/controllers/admins_controller.rb
  app/helpers/admin_access_helper.rb
  app/models/user.rb
  app/models/user_access.rb
  app/models/user_access_tree.rb
  app/views/admins/_form.html.erb
  app/views/email_authentications/invitations/_access_tree.html.erb
  app/views/email_authentications/invitations/new.html.erb
Labels: simple-permissions

#1291 Reports: Copy updates
  app/views/reports/regions/show.html.erb
Labels: reports

#1290 Reports: "Users to review" card mobile ordering
  app/assets/stylesheets/application.scss
  app/views/my_facilities/index.html.erb
  app/views/organizations/index.html.erb
  app/views/shared/_user_approvals.html.erb
Labels: reports

#1286 Miscellaneous permissions fixes
  app/controllers/admin/users_controller.rb
  app/controllers/my_facilities_controller.rb
  app/controllers/organizations_controller.rb
  app/models/user_access.rb
  app/views/admin/users/index.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_paginate_and_filter_by_district.html.erb
  app/views/shared/_user_approvals.html.erb
  config/routes.rb
Labels: simple-permissions

#1265 Selectively decide access tree depth + better access level dropdown
  .standard_todo.yml
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/common/invite_admin.js
  app/assets/javascripts/common/polyfill.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/admin/_access_tree.scss
  app/assets/stylesheets/partials/admin/_form.scss
  app/assets/stylesheets/partials/admin/_index.scss
  app/assets/stylesheets/partials/admin/_show.scss
  app/controllers/admins_controller.rb
  app/helpers/admin_access_helper.rb
  app/models/user.rb
  app/models/user_access.rb
  app/models/user_access_tree.rb
  app/presenters/admin_access_presenter.rb
  app/views/admins/_form.html.erb
  app/views/admins/index.html.erb
  app/views/admins/show.html.erb
  app/views/email_authentications/invitations/_access_tree.html.erb
  app/views/email_authentications/invitations/_facility_access_tree.html.erb
  app/views/email_authentications/invitations/_facility_group_access_tree.html.erb
  app/views/email_authentications/invitations/_organization_access_tree.html.erb
  app/views/email_authentications/invitations/new.html.erb
  app/views/layouts/application.html.erb
  config/locales/en.yml
Labels: simple-permissions

#1281 Permissions UI tweaks
  app/assets/javascripts/common/invite_admin.js
  app/assets/stylesheets/partials/admin/_access_tree.scss
  app/assets/stylesheets/partials/admin/_form.scss
  app/assets/stylesheets/partials/admin/_show.scss
  app/controllers/admins_controller.rb
  app/controllers/email_authentications/invitations_controller.rb
  app/helpers/admin_access_helper.rb
  app/models/user_access.rb
  app/models/user_access_tree.rb
  app/views/admins/_form.html.erb
  app/views/admins/edit.html.erb
  app/views/admins/show.html.erb
  app/views/email_authentications/invitations/_facility_access_tree.html.erb
  app/views/email_authentications/invitations/_facility_group_access_tree.html.erb
  app/views/email_authentications/invitations/_organization_access_tree.html.erb
  app/views/email_authentications/invitations/new.html.erb
Labels: simple-permissions

#1268 Teleconsult MO sync endpoint
  app/controllers/api/v4/facility_medical_officers_controller.rb
  app/schema/api/v4/models.rb
  app/schema/api/v4/schema.rb
  app/transformers/api/v4/teleconsultation_medical_officer_transformer.rb
  config/routes.rb
  spec/api/v4/teleconsultation_medical_officers_spec.rb
  spec/controllers/api/v4/facility_medical_officers_controller_spec.rb
  spec/transformers/api/v4/teleconsultation_medical_officer_transformer_spec.rb
  swagger/v4/swagger.json
Labels: telemed-mvp

#1295 Refactor permissions specs
  app/models/user_access.rb
  spec/models/user_access_spec.rb
Labels: simple-permissions

#1299 A few quick fixes around permissions
  app/controllers/admins_controller.rb
  app/controllers/email_authentications/invitations_controller.rb
  app/helpers/admin_access_helper.rb
  app/models/user.rb
  app/models/user_access.rb
  app/views/admins/_form.html.erb
  app/views/admins/edit.html.erb
  app/views/admins/index.html.erb
  app/views/layouts/application.html.erb
  db/migrate/20200908183016_add_index_to_access_resources.rb
  db/schema.rb
  spec/controllers/admins_controller_spec.rb
  spec/factories/accesses.rb
  spec/factories/users.rb
  spec/models/user_access_spec.rb
Labels: simple-permissions

#1306 Migrate Appointments Controller
  app/controllers/appointments_controller.rb
  app/views/appointments/index.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/overdue.html.erb
  app/views/shared/_paginate_and_filter_by_facility.html.erb
  spec/features/appointments_with_new_permissions_spec.rb
Labels: simple-permissions

#1303 Gate RegionsController for new permissions
  app/controllers/reports/regions_controller.rb
  app/views/reports/regions/details.html.erb
  app/views/reports/regions/index.html.erb
Labels: simple-permissions

#1304 Gate Analytics Controllers and views
  app/controllers/analytics/districts_controller.rb
  app/controllers/analytics/facilities_controller.rb
  app/controllers/analytics_controller.rb
  app/views/analytics/districts/show.html.erb
  app/views/analytics/facilities/show.html.erb
  app/views/layouts/application.html.erb
  app/views/reports/regions/show.html.erb
  app/views/shared/_analytics_table.html.erb
Labels: simple-permissions

#1297 Improve user acess tree loading performance
  Gemfile
  Gemfile.lock
  app/assets/javascripts/common/admins.js
  app/assets/javascripts/common/invite_admin.js
  app/assets/stylesheets/partials/admin/_access_tree.scss
  app/controllers/admins_controller.rb
  app/helpers/admin_access_helper.rb
  app/models/user_access_tree.rb
  app/presenters/admin_access_presenter.rb
  app/views/admins/_form.html.erb
  app/views/admins/edit.html.erb
  app/views/admins/show.html.erb
  app/views/email_authentications/invitations/_facility_access_tree.html.erb
  app/views/email_authentications/invitations/_facility_group_access_tree.html.erb
  app/views/email_authentications/invitations/_organization_access_tree.html.erb
  app/views/email_authentications/invitations/new.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  spec/controllers/admins_controller_spec.rb
  spec/models/user_access_spec.rb
  spec/presenters/admin_access_presenter_spec.rb
Labels: simple-permissions

#1313 Minor permissions fixes/improvements
  app/controllers/admin/facilities_controller.rb
  app/controllers/admin/facility_groups_controller.rb
  app/controllers/admin/organizations_controller.rb
  app/controllers/admins_controller.rb
  app/helpers/admin_access_helper.rb
  app/models/facility.rb
  app/models/facility_group.rb
  app/models/organization.rb
  app/views/admin/facilities/edit.html.erb
  app/views/admin/facility_groups/edit.html.erb
  app/views/admin/organizations/index.html.erb
  app/views/layouts/application.html.erb
  spec/models/facility_group_spec.rb
  spec/models/facility_spec.rb
  spec/models/organization_spec.rb
Labels: simple-permissions

#1312 Migrate admins from old user permissions to new
  lib/tasks/scripts/create_accesses_from_permissions.rb
  spec/factories/users.rb
  spec/lib/tasks/scripts/create_accesses_from_permissions_spec.rb
Labels: simple-permissions

#1319 Fix some more minor permissions-related regressions
  app/controllers/admin/facilities_controller.rb
  app/controllers/concerns/my_facilities_filtering.rb
  app/controllers/email_authentications/invitations_controller.rb
  app/controllers/my_facilities_controller.rb
  app/models/user_access.rb
  app/presenters/admin_access_presenter.rb
  app/views/admin/users/_form.html.erb
  lib/tasks/scripts/create_accesses_from_permissions.rb
  spec/controllers/admins_controller_spec.rb
Labels: simple-permissions

#1310 Migrate teleconsult MOs to MVP
  config/schedule.rb
  lib/tasks/link_teleconsultation_medical_officers.rake
  lib/tasks/scripts/link_teleconsultation_medical_officers.rb
  spec/tasks/scripts/link_teleconsultation_medical_officers_spec.rb
Labels: telemed-mvp

#1322 Migrate approval notifier emails to also use new permissions
  app/mailers/approval_notifier_mailer.rb
  spec/mailers/approval_notifier_mailer_spec.rb
  spec/mailers/previews/approval_notifier_preview.rb
Labels: simple-permissions

#1316 Teleconsult sync API
  app/controllers/api/v4/teleconsultations_controller.rb
  app/models/facility.rb
  app/models/facility_group.rb
  app/models/teleconsultation.rb
  app/models/user.rb
  app/schema/api/v4/models.rb
  app/schema/api/v4/schema.rb
  app/services/merge_teleconsultation_service.rb
  app/transformers/api/v4/teleconsultation_transformer.rb
  app/validators/api/v4/teleconsultation_payload_validator.rb
  config/routes.rb
  db/migrate/20200914073359_create_teleconsultations.rb
  db/schema.rb
  spec/api/v4/teleconsultations_spec.rb
  spec/controllers/api/v3/patients_controller_spec.rb
  spec/controllers/api/v4/teleconsultations_controller_spec.rb
  spec/factories/teleconsultations.rb
  spec/models/facility_group_spec.rb
  spec/models/facility_spec.rb
  spec/models/teleconsultation_spec.rb
  spec/payloads/api/v4/teleconsultation_payload_validator_spec.rb
  spec/services/merge_teleconsultation_service_spec.rb
  spec/transformers/api/v4/teleconsultation_transformer_spec.rb
  spec/utils.rb
  swagger/v4/swagger.json
Labels: telemed-mvp

#1320 Telemed: Add fields to PrescriptionDrug
  app/controllers/api/v3/prescription_drugs_controller.rb
  app/models/patient.rb
  app/models/prescription_drug.rb
  app/models/teleconsultation.rb
  app/schema/api/v3/models.rb
  app/validators/api/v3/prescription_drug_payload_validator.rb
  db/migrate/20200917184207_add_columns_to_prescription_drugs.rb
  db/schema.rb
  spec/controllers/api/v3/prescription_drugs_controller_spec.rb
  spec/exporters/patients_exporter_spec.rb
  spec/factories/prescription_drugs.rb
  spec/models/prescription_drug_spec.rb
  spec/models/teleconsultation_spec.rb
  swagger/v3/swagger.json
Labels: telemed-mvp

#1296 Assigned facility reports
  app/assets/stylesheets/partials/_dashboard.scss
  app/assets/stylesheets/partials/_reports.scss
  app/models/facility_group.rb
  app/models/latest_blood_pressures_per_patient_per_day.rb
  app/queries/my_facilities/blood_pressure_control_query.rb
  app/queries/my_facilities/missed_visits_query.rb
  app/queries/my_facilities/overview_query.rb
  app/queries/my_facilities/registrations_query.rb
  app/services/cohort_service.rb
  app/services/control_rate_service.rb
  app/services/no_bp_measure_service.rb
  app/views/reports/regions/cohort.html.erb
  app/views/reports/regions/details.html.erb
  app/views/reports/regions/show.html.erb
  db/migrate/20200904102220_add_indices_to_matviews.rb
  db/migrate/20200904103339_drop_daily_bp_matview.rb
  db/schema.rb
  lib/tasks/refresh_materialized_db_views.rake
  spec/models/facility_group_spec.rb
  spec/models/latest_blood_pressures_per_patient_per_day_spec.rb
  spec/services/control_rate_service_spec.rb
  spec/services/no_bp_measure_service_spec.rb
Labels: assigned-facilities

#1321 More polishing and more regression clean-ups for permissions
  app/assets/javascripts/common/admins.js
  app/assets/stylesheets/partials/admin/_form.scss
  app/controllers/admin/facilities_controller.rb
  app/controllers/admin/organizations_controller.rb
  app/controllers/admins_controller.rb
  app/controllers/email_authentications/invitations_controller.rb
  app/helpers/admin_access_helper.rb
  app/presenters/admin_access_presenter.rb
  app/views/admin/facilities/show.html.erb
  app/views/admin/facilities/upload.html.erb
  app/views/admins/_form.html.erb
  app/views/layouts/application.html.erb
  spec/controllers/admins_controller_spec.rb
  spec/controllers/email_authentications/invitations_controller_spec.rb
Labels: simple-permissions

#1317 Misc updates to the new permission UI
  app/assets/javascripts/common/admins.js
  app/assets/stylesheets/partials/admin/_access_tree.scss
  app/views/admins/_form.html.erb
  app/views/email_authentications/invitations/_facility_access_tree.html.erb
  app/views/email_authentications/invitations/_facility_group_access_tree.html.erb
  app/views/email_authentications/invitations/_organization_access_tree.html.erb
  app/views/email_authentications/invitations/new.html.erb
Labels: simple-permissions

#1345 Fix UI regression in ProtocolDrugs creation
  app/controllers/admin_controller.rb
  app/views/admin/protocol_drugs/index.html.erb
  app/views/admin/protocols/index.html.erb
  app/views/admin/protocols/show.html.erb
  spec/controllers/admin_controller_spec.rb
Labels: bug, simple-permissions

#1344 Bug: Total count not updating when user has only facility-level access tree
  app/assets/javascripts/common/admins.js
Labels: bug, simple-permissions

#1169 Assigned facility: Query updates
  app/assets/stylesheets/partials/_dashboard.scss
  app/assets/stylesheets/partials/_reports.scss
  app/assets/stylesheets/partials/_spacing.scss
  app/controllers/analytics_controller.rb
  app/controllers/appointments_controller.rb
  app/controllers/my_facilities_controller.rb
  app/exporters/patients_exporter.rb
  app/exporters/patients_with_history_exporter.rb
  app/jobs/patient_list_download_job.rb
  app/models/facility.rb
  app/models/facility_group.rb
  app/models/latest_blood_pressures_per_patient_per_day.rb
  app/models/organization_district.rb
  app/queries/cohort_analytics_query.rb
  app/queries/district_analytics_query.rb
  app/queries/facility_analytics_query.rb
  app/queries/my_facilities/blood_pressure_control_query.rb
  app/queries/my_facilities/missed_visits_query.rb
  app/queries/my_facilities/overview_query.rb
  app/queries/my_facilities/registrations_query.rb
  app/services/cohort_service.rb
  app/services/control_rate_service.rb
  app/services/no_bp_measure_service.rb
  app/views/analytics/districts/_analytics_table.html.erb
  app/views/analytics/districts/show.csv.erb
  app/views/analytics/districts/show.html.erb
  app/views/analytics/facilities/_analytics_table.html.erb
  app/views/analytics/facilities/show.csv.erb
  app/views/analytics/facilities/show.html.erb
  app/views/my_facilities/blood_pressure_control.html.erb
  app/views/my_facilities/missed_visits.html.erb
  app/views/reports/regions/_facility_tables.html.erb
  app/views/reports/regions/cohort.html.erb
  app/views/reports/regions/details.html.erb
  app/views/reports/regions/show.html.erb
  app/views/shared/_cohort_charts.html.erb
  db/migrate/20200810095935_update_patient_summaries_to_version_4.rb
  db/migrate/20200904102220_add_indices_to_matviews.rb
  db/migrate/20200904103339_drop_daily_bp_matview.rb
  db/schema.rb
  db/views/patient_summaries_v04.sql
  lib/tasks/refresh_materialized_db_views.rake
  spec/controllers/analytics/districts_controller_spec.rb
  spec/controllers/analytics/facilities_controller_spec.rb
  spec/controllers/appointments_controller_spec.rb
  spec/exporters/patients_exporter_spec.rb
  spec/exporters/patients_with_history_exporter_spec.rb
  spec/jobs/patient_list_download_job_spec.rb
  spec/models/facility_group_spec.rb
  spec/models/facility_spec.rb
  spec/models/latest_blood_pressures_per_patient_per_day_spec.rb
  spec/models/organization_district_spec.rb
  spec/queries/cohort_analytics_query_spec.rb
  spec/queries/district_analytics_query_spec.rb
  spec/queries/facility_analytics_query_spec.rb
  spec/queries/my_facilities/blood_pressure_control_query_spec.rb
  spec/queries/my_facilities/missed_visits_query_spec.rb
  spec/services/control_rate_service_spec.rb
  spec/services/no_bp_measure_service_spec.rb
Labels: assigned-facilities

#1353 Minor UI fixes for the permissions UI
  app/assets/stylesheets/partials/admin/_form.scss
Labels: simple-permissions

#1361 Reports: Update 3rd card to "Missed visits"
  app/assets/javascripts/common/reports.js
  app/assets/stylesheets/partials/_reports.scss
  app/views/reports/regions/_facility_tables.html.erb
  app/views/reports/regions/show.html.erb
Labels: reports

#1358 Reports copy fixes
  app/views/reports/regions/show.html.erb
Labels: reports

#1360 Reports dropdown alignment fix
  app/views/reports/regions/_downloads.html.erb
  app/views/reports/regions/_header.html.erb
Labels: reports
