Repository simpledotorg/simple-server, pull requests merged in 2021-07, with the labels that each got.

#2701 Show user typo fix
  app/views/shared/_recent_bp_log.html.erb
Labels: bug

#2597 Feature flag drug stock for districts instead of users
  app/controllers/api/v3/analytics/user_analytics_controller.rb
  app/controllers/concerns/my_facilities_filtering.rb
  app/controllers/my_facilities/drug_stocks_controller.rb
  app/models/concerns/flipperable.rb
  app/models/region.rb
  app/models/user.rb
  app/views/api/v3/analytics/user_analytics/show.html.erb
  app/views/layouts/my_facilities.html.erb
  lib/seed/runner.rb
  spec/models/region_spec.rb
  spec/models/user_spec.rb
Labels: do-not-merge

#2519 Fix: Integers not being filtered from logs
  config/initializers/filter_parameter_logging.rb
Labels: stale-pr

#2586 3406 ab testing architecture docs
  doc/arch/017-ab-testing.md
  doc/wiki/running-ab-experiments.md
Labels: stale-pr
